### ISSUE TITLE
Internet Permission not specified.

### ISSUE THREAD

**Issue by avinash-viva** [magnetsystems/r2m-plugin-android#21]
Tried one sample, and it ran successfully.
Later I realized that I never added Internet Permission in my manifest file, how come it still fetches data?

**Comment by etexier** [comment]
The "Add REST API" wizard runs within your IDE, not your app. It is similar to REST clients you'd find on most browsers and is only used at design time to create your client classes. 
Once you're ready to call these generated classes within your app, then, of course,  you'll must enable Internet permission.

**Comment by hcdclb** [comment]
The Internet permission is specified in the Android manifest of Rest2Mobile aar library. If you crack open the aar, you will see it in "AndroidManifest.xml"

**Comment by avinash-viva** [comment]
@hcdclb, thanks for the answer. I believe that should be the case which didn't occur to me. Will close the issue.

@etexier, although points to different context, appreciate your gesture. Thanks.
