### ISSUE TITLE
Dracula theme: JSON response hard to read

### ISSUE THREAD

**Issue by etexier** [magnetsystems/r2m-plugin-android#4]
To track magnet field reported issue:  https://github.com/magnetsystems/fieldeng/issues/105
When switching Android Studio's theme to dark (Dracula), the JSON response is red-ish on dark grey background and pretty difficult to read.

I'm not sure if we have control over the color of the fonts, or if this is automatically determined by the theme.

Note other IDEA plugin ran into the same issue: see for instance ,https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/dfd738b62113b17f0d52b325939e9dc171a287c3

**Comment by Moter8** [comment]
Looks like this today, not the best but not terrible either, maybe a lighter color would be nice? (Or close this issue)
![1](http://i.imgur.com/0s1uTTO.png)

**Comment by etexier** [comment]
fixed in 1.1.9
